### ISSUE TITLE
uncaught exception: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by RP70DP** [iobroker-community-adapters/ioBroker.hmip#111]
JS-Controller 3.0.20:

`hmip.0	2020-05-01 23:00:00.276	error	at Receiver.startLoop (/opt/iobroker/node_modules/iobroker.hmip/node_modules/ws/lib/receiver.js:138:22)
hmip.0	2020-05-01 23:00:00.276	error	at Receiver.getData (/opt/iobroker/node_modules/iobroker.hmip/node_modules/ws/lib/receiver.js:352:17)
hmip.0	2020-05-01 23:00:00.276	error	at Receiver.dataMessage (/opt/iobroker/node_modules/iobroker.hmip/node_modules/ws/lib/receiver.js:413:14)
hmip.0	2020-05-01 23:00:00.276	error	at Receiver.emit (events.js:310:20)
hmip.0	2020-05-01 23:00:00.276	error	at Receiver.receiverOnMessage (/opt/iobroker/node_modules/iobroker.hmip/node_modules/ws/lib/websocket.js:800:20)
hmip.0	2020-05-01 23:00:00.276	error	at WebSocket.emit (events.js:310:20)
hmip.0	2020-05-01 23:00:00.276	error	at WebSocket.<anonymous> (/opt/iobroker/node_modules/iobroker.hmip/api/hm-cloud-api.js:152:18)
hmip.0	2020-05-01 23:00:00.276	error	at HmCloudAPI._parseEventdata (/opt/iobroker/node_modules/iobroker.hmip/api/hm-cloud-api.js:200:22)
hmip.0	2020-05-01 23:00:00.276	error	at HmIpCloudAccesspointAdapter._eventRaised (/opt/iobroker/node_modules/iobroker.hmip/main.js:288:28)
hmip.0	2020-05-01 23:00:00.276	error	at HmIpCloudAccesspointAdapter._updateHomeStates (/opt/iobroker/node_modules/iobroker.hmip/main.js:808:58)
hmip.0	2020-05-01 23:00:00.276	error	(419) TypeError: Cannot read property 'id' of undefined
hmip.0	2020-05-01 23:00:00.265	error	(419) uncaught exception: Cannot read property 'id' of undefined`

**Comment by RP70DP** [comment]
`2020-05-02 01:51:35.151  - [35msilly[39m: hmip.0 (2345) _updateHomeStates - {"weather":{"temperature":6.5,"weatherCondition":"CLOUDY_WITH_RAIN","weatherDayTime":"NIGHT","minTemperature":6.1,"maxTemperature":6.7,"humidity":89,"windSpeed":6.444,"windDirection":242,"vaporAmount":6.668815299064463},"metaGroups":
2020-05-02 01:51:35.155  - [35msilly[39m: hmip.0 (2345) _updateHomeStates - undefined
2020-05-02 01:51:35.156  - [35msilly[39m: hmip.0 (2345) _updateGroupStates - {"id":"XXX","homeId":"XXX","metaGroupId":null,"label":"SIREN","lastStatusUpdate":1588377093232,"unreach":false,"lowBat":false,"dutyCycle":false,"type":"ALARM_SWITCHING","channels":[{"deviceId":"XXX","channelIndex":1},{"deviceId":"XXX","channelIndex":1}],"on":false,"dimLevel":null,"onTime":180,"signalAcoustic":"FREQUENCY_RISING","signalOptical":"DOUBLE_FLASHING_REPEATING","smokeDetectorAlarmType":null,"acousticFeedbackEnabled":true}
2020-05-02 01:51:35.157  - [31merror[39m: hmip.0 (2345) uncaught exception: Cannot read property 'id' of undefined
2020-05-02 01:51:35.159  - [31merror[39m: hmip.0 (2345) TypeError: Cannot read property 'id' of undefined
    at HmIpCloudAccesspointAdapter._updateHomeStates (/opt/iobroker/node_modules/iobroker.hmip/main.js:808:58)
    at HmIpCloudAccesspointAdapter._eventRaised (/opt/iobroker/node_modules/iobroker.hmip/main.js:288:28)
    at HmCloudAPI._parseEventdata (/opt/iobroker/node_modules/iobroker.hmip/api/hm-cloud-api.js:200:22)
    at WebSocket.<anonymous> (/opt/iobroker/node_modules/iobroker.hmip/api/hm-cloud-api.js:152:18)
    at WebSocket.emit (events.js:310:20)
    at Receiver.receiverOnMessage (/opt/iobroker/node_modules/iobroker.hmip/node_modules/ws/lib/websocket.js:800:20)
    at Receiver.emit (events.js:310:20)
    at Receiver.dataMessage (/opt/iobroker/node_modules/iobroker.hmip/node_modules/ws/lib/receiver.js:413:14)
    at Receiver.getData (/opt/iobroker/node_modules/iobroker.hmip/node_modules/ws/lib/receiver.js:352:17)
    at Receiver.startLoop (/opt/iobroker/node_modules/iobroker.hmip/node_modules/ws/lib/receiver.js:138:22)
2020-05-02 01:51:35.160  - [32minfo[39m: hmip.0 (2345) cleaned everything up...`

**Comment by Apollon77** [comment]
Scheinbar wetterdaten kommen ohne id. Ich schau mal

**Comment by RP70DP** [comment]
Has been fixed with v1.0.0.
